### ISSUE TITLE
Bot doesn't reply

### ISSUE THREAD

**Issue by Spigushe** [Cyantoo/MTGBot#2]
I followed every steps and I can't open the DiscordClient.py :
`File "/Users/spigushe/Desktop/MTGBot-master/DiscordClient.py", line 11
    async def on_ready():
        ^
SyntaxError: invalid syntax`

The `^` is pointing to `async`. Is there something to change in the code or anywhere ?

**Comment by Cyantoo** [comment]
What version of Python do you use? Please make sure you use the latest version (async is not supported in Python 2.7 in particular, I think).

**Comment by Spigushe** [comment]
It was a problem with my Python Launcher what started python 2.7 instead of Python 3.5

I just got another problem : I asked for a card `[Greater Auramancy]` and the bot didn't reply. Here is the log of it :

![capture d ecran 2016-11-21 a 18 51 00](https://cloud.githubusercontent.com/assets/6403098/20494045/80290976-b01b-11e6-87bf-fec891e1faf3.png)

```
New message
Request : Greater Auramancy
Ignoring exception in on_message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/Users/spigushe/Desktop/MTGBot-master/DiscordClient.py", line 34, in on_message
    msg_list = ask_api.ask_card(requete)
  File "/Users/spigushe/Desktop/MTGBot-master/ask_api.py", line 5, in ask_card
    cards = Card.where(name=cardname).all()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mtgsdk/querybuilder.py", line 79, in all
    response = RestClient.get(url, self.params)[self.type.RESOURCE]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mtgsdk/restclient.py", line 34, in get
    response = json.loads(urlopen(req).read().decode("utf-8"))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)>
```

**Comment by Cyantoo** [comment]
Sorry for the late reply. It looks like a problem with the connection to Internet. Do you still have this problem? Do you have this problem with all cards or only this one?
